/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecondTestRouteImport } from './routes/secondTest'
import { Route as IndexRouteImport } from './routes/index'

const SecondTestRoute = SecondTestRouteImport.update({
  id: '/secondTest',
  path: '/secondTest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secondTest': typeof SecondTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/secondTest': typeof SecondTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/secondTest': typeof SecondTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/secondTest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/secondTest'
  id: '__root__' | '/' | '/secondTest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecondTestRoute: typeof SecondTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secondTest': {
      id: '/secondTest'
      path: '/secondTest'
      fullPath: '/secondTest'
      preLoaderRoute: typeof SecondTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecondTestRoute: SecondTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
